Repository lucasresck/gnome-shell-extension-alt-tab-scroll-workaround, pull requests merged in 2023-11, with the labels that each got.

#21 GNOME 45
  extension.js
  metadata.json
Labels: bug, help wanted

#25 Add support to overview + mouse click
  extension.js
Labels: bug, enhancement

#27 Update extension to GNOME 45, add support to `Alt+Esc`, and add support to overview + mouse click
  README.md
  extension.js
  metadata.json
Labels: enhancement

#29 Destroy all objects
  extension.js
Labels: enhancement
